platforms/Windows/CustomActions/SwiftInstaller/Headers/logging.hh, platforms/Windows/CustomActions/SwiftInstaller/Headers/scoped_raii.hh, platforms/Windows/CustomActions/SwiftInstaller/Headers/swift_installer.hh, platforms/Windows/CustomActions/SwiftInstaller/Sources/dllmain.cc, platforms/Windows/CustomActions/SwiftInstaller/Sources/logging.cc, platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc, platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj, platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj.filters, platforms/Windows/CustomActions/SwiftInstaller/ThirdParty/Microsoft.VisualStudio.Setup.Configuration.Native/inc/Setup.Configuration.h
This adds the custom action that is needed for the Swift Installer.
This is responsible for automating the deployment of the support files
for the Windows SDK and Visual C++ SDK.
=> Windows: add Swift installer custom action

platforms/Windows/toolchain.wixproj
The `DisplayBuildConfiguration` pre-build task is not particularly
useful with a single build configuration, remove the vestigial
reference.
=> Windows: remove pre-build task on toolchain package

platforms/Windows/toolchain.wxs
The product version is passed as a constant and thus must be referenced
as `var.ProductVersion`.  Update the references accordingly.
=> Windows: correct variable reference for `ProductVersion`

platforms/Windows/toolchain.wxs
The new style media handling doesn't seem to work due to the naming of
the cabinet.  Simply fallback to the old schema for now.
=> Windows: fall back to old style of media handling

platforms/Windows/CustomActions/SwiftInstaller/Headers/logging.hh, platforms/Windows/CustomActions/SwiftInstaller/Headers/scoped_raii.hh, platforms/Windows/CustomActions/SwiftInstaller/Headers/swift_installer.hh, platforms/Windows/CustomActions/SwiftInstaller/Sources/dllmain.cc, platforms/Windows/CustomActions/SwiftInstaller/Sources/logging.cc, platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc, platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj, platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj.filters
This restores the SwiftInstaller custom action, relicensed under the
Apache 2.0.  The third party dependency on the Microsoft code is now
managed via nuget, and will be fetched as appropriate when building.
=> Windows: restore SwiftInstaller Custom Action

platforms/Windows/sdk.wixproj, platforms/Windows/sdk.wxs
This adds the WiX packaging rules for creating the X86_64 SDK MSI.  This
has been modified to update the copyright holder and removal of the
TensorFlow support as well as using the modern structure for the
installed image.
=> Windows: add the packaging for the SDK

platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj
The platform name is `Win32` rather than `x86` (the short name).  This
should allow building the SDK MSI.
=> Windows: tweak the custom action platform

platforms/Windows/sdk.wxs
Remove a stray space and an accidental paste of a value.
=> Windows: correct some errors in the SDK manifest

platforms/Windows/sdk.wxs
Fix a typo in the reference to the `_DISTRIBUTED_IMPORT_LIBS` component.
=> Windows: correct typo of distributed for import libs

platforms/Windows/devtools.wixproj, platforms/Windows/devtools.wxs
This adds the build support for the devtools MSI which packages the
tools such as SPM and LSP.
=> Windows: add developer tools packaging rules

icu.wixproj, icu.wxs
We currently split up the ICU packaging as it is not part of the
toolchain but a required dependency and the version must match.
=> Windows: add ICU packaging rules

platforms/Windows/icu.wxs
The library should be versioned with the full version, not just the
major version.
=> Windows: correct ICU location

runtime.wixproj, runtime.wxs
This adds the packaging for the Windows runtime (the redistributable
part of the SDK).
=> Windows: add runtime packaging scripts

platforms/Linux/Fedora/Dockerfile, platforms/Linux/Fedora/README.md, platforms/Linux/Fedora/build_swift_rpm.sh, platforms/Linux/Fedora/nocyclades.patch, platforms/Linux/Fedora/pc-circular-dependencies-optimization.patch, platforms/Linux/Fedora/swift-for-fedora.patch, platforms/Linux/Fedora/swift-lang.spec, platforms/Linux/Fedora/unusedvariable.patch
This PR includes all the files necessary to build Swift under Fedora, either as a container or locally. The instructions for both are in the `README.md` file. 
The spec file and patches are for building Swift 5.5-RELEASE. It's my goal to, for subsequent Swift versions, to eliminate the patches via PRs to the appropriate projects.
=> Initial commit of build instructions for Swift under Fedora Linux

platforms/Linux/centos/8/swift-lang.spec
initial commit had copy/paste license from fedora spec. this is licensed under apache 2.0
=> fix license

platforms/Linux/centos/7/build_rpm.sh
```
[swift/utils/build-script] ERROR: can't find clang (please install clang-3.5 or a later version)
ERROR: command terminated with a non-zero exit status 1, aborting
```
We were missing these two steps from CentOS 7 Dockerfile: 
```
RUN echo -e ". /opt/rh/sclo-git25/enable\n. /opt/rh/llvm-toolset-7/enable\n. /opt/rh/devtoolset-8/enable\n" >> /home/build-user/.bashrc
RUN sed -i -e 's/\*__block/\*__libc_block/g' /usr/include/unistd.h
```
=> Support newer Clang in CentOS 7

platforms/Linux/amazonlinux/2/Dockerfile, platforms/Linux/amazonlinux/2/build_rpm.sh, platforms/Linux/amazonlinux/2/swiftlang.spec, platforms/Linux/centos/7/Dockerfile, platforms/Linux/centos/7/build_rpm.sh, platforms/Linux/centos/7/swiftlang.spec, platforms/Linux/centos/8/swiftlang.spec
```
---------------------------------------------
Error when bootstrapping CMake:
Cannot find appropriate Makefile processor on this system.
Please specify one using environment variable MAKE.
---------------------------------------------
```
=> Fix python3 six and make issue on Amazon Linux 2

platforms/Windows/devtools.wxs
This adds the new Swift Package Manager content from
apple/swift-package-manager#3879 to the installation manifest.
=> Windows: add PackageFingerprint.dll to Windows install

platforms/Windows/devtools.wxs, platforms/Windows/toolchain.wixproj, platforms/Windows/toolchain.wxs
This shuffles the swift-driver from devtools to toolchain, replacing the
driver from the swift repository at packaging time.  This is required to
be this way to support bootstrapping and more importantly, to reduce the
overall build times for the toolchain (OSS builders are perilously close
to the time limit, and would fail to build with swift-driver in the same
build).  The toolchain MSI is meant to contain everything that is needed
for building a program manually with the compiler.  This should allow us
to migrate to swift-driver as the official Windows driver.
=> Windows: shuffle files in the MSI packaging

platforms/Windows/toolchain.wxs
With the migration to Yams 5.0.0, `CYaml.dll` is no longer distributed
as it is fully internalized into `Yams.dll`.
=> Windows: drop `CYaml.dll`

platforms/Windows/toolchain.wxs
This repairs the toolchain manifest after apple/swift#39441 which split
the header into two files.  This ensures that both halves are packaged.
=> Windows: add SwiftSyntaxCDataTypes.h to the toolchain

platforms/Windows/toolchain.wxs
This repairs the toolchain manifest after apple/swift#39441 which split
the header into two files.  This ensures that both halves are packaged.
=> [5.6] Windows: add SwiftSyntaxCDataTypes.h to the toolchain

platforms/Windows/devtools.wxs
With SK-LSP building the LSP with static linking, the fileset for the
server are now different.  Update to remove the files that are no longer
distributed individually.
=> Windows: update packaging manifest for SK-LSP changes

platforms/Windows/devtools.wxs
The switch to swift-driver as the language driver forced a shuffling of
the files.  In the process, llbuild and Yams were moved into the
toolchain MSI as they are required for using the toolchain.
Furthermore, CYaml is no longer even available as it now is statically
linked into the Yams library.  Remove the references to their content.
=> Windows: clean up manifest file for devtools

platforms/Linux/RPM/Amazonlinux/2/swiftlang.spec, platforms/Linux/RPM/Centos/7/swiftlang.spec, platforms/Linux/RPM/Centos/8/swiftlang.spec
motivation: static linking required the development version of libxml2 and libcurl
changes: include libxml2-devel and libcurl-devel which are needed for static linking
=> update RPM specs dependencies

platforms/Linux/RPM/Centos/7/swiftlang.spec, platforms/Linux/RPM/Centos/8/swiftlang.spec, platforms/Linux/RPM/Fedora/34/swiftlang.spec, platforms/Linux/RPM/Fedora/35/swiftlang.spec, platforms/Linux/RPM/Fedora/rawhide/swiftlang.spec
motivation: easier to maintain code
changes:
* sort BuildRequires, Requires and move secions alphabetically
* other small formatting fixes like whitespace, etc
* remove cmake from fedora BuildRequires since we are builfing it from source
* update fedora rawhide path to be more consistent with other fedora locations and rpm builders
=> improve RPM spec formatting

platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc
Move the previous VS2019 names which are the current latest to the top
of the list.  Update the VS2019 toolset names to match that from VS2022
as the current name will take care of VS2019 case.  Additionally, add
the VS2022 toolset names to the list.  This allows this custom action to
support VS2017, VS2019, and VS2022.
=> CustomAction: update the known toolset list

platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc
VS2022 adjusted the layout of the default toolset configuration.  Prefer
the versioned format over the unversioned format to retain compatibility
with VS2019.  This extends coverage for VS2022 and stays compatible with
VS2017, VS2019, and VS2022.
=> SwiftInstaller: update the default file list

platforms/Windows/sdk.wxs
Update the SDK installation to rename the swiftmodule and swiftdoc files
for XCTest into the modern layout.  This will result in the construction
of a module directory rather than the freestanding files.
=> WiX: address FIXME in sdk.wxs

platforms/Windows/devtools.wixproj, platforms/Windows/devtools.wxs, platforms/Windows/icu-amd64.wxs, platforms/Windows/icu.wixproj, platforms/Windows/installer.wixproj, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime.wixproj, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk.wixproj, platforms/Windows/toolchain.wxs
This renames the files to allow for extending the SDK/runtime packaging
for additional architectures, which enables packaging the SDK/runtime
for x86 and ARM64.  Update the other wixproj files to maintain
similarity in property group setup.
=> WiX: make SDK/runtime manifests multi-use

platforms/Windows/sdk-amd64.wxs, platforms/Windows/toolchain.wxs
This variable is more about where the toolchain is located rather than
the SDK.  It was previously setup by the SDK MSI as the variable really
is currently only used for locating XCTest.  However, it is possible to
locate XCTest via the SDKROOT path which is likely better in any case.
This will allow us to now conditionalise the "installation" of the
SDKROOT variable to the case where the SDK matches the host.  In
particular, only two hosts will ever be permitted to set this variable:
x64 and ARM64 and only when the native SDK is installed.  For any other
case, the user is responsible for setting SDKROOT or passing `-sdk` as
it implies cross-compilation.
=> WiX: move `DEVELOPER_DIR` to be setup by the toolchain MSI

platforms/Windows/sdk-amd64.wxs
The rest of the Windows setup is properly configured for multiple
parallel SDKs and versions.  However, the XCTest import library (which
would not be a problem if all SDKs were guaranteed to be installed and
we did some pre-processing before building the MSIs) and more
importantly the runtime DLL for all architectures is in a singular
location.  This would be a problem for installing multiple SDKs for the
same platform but multiple architectures.  Now that we are getting
closer to the multi-architecture cross-compiling details being
finalized, we need to repair this oversight.
This breaks the layout and compatibility with older toolchains.
However, it is something that the user _could_ workaround if they are
sufficiently motivated (it requires additional flags to be explicitly
specified). …
=> WiX: restructure XCTest in SDK

platforms/Windows/icu-amd64.wxs, platforms/Windows/runtime-amd64.wxs
Re-home the runtime into a better default location on AMD64:
`%ProgramFiles%\swift\runtime-[VERSION]` from the previous
`%SystemDrive%\Library\Swift-[VERSION]`.  This will be required to
ensure that not only can we parallel install x86 and x64, but also
prepares the installers to accommodate alternate install locations.
Take the opportunity to restore the missing `usr` directory for the
runtime image.
Simultaneously, relocate ICU from `%SystemDrive%\icu-[VERSION]` to a new
peered location at `%ProgramFiles%\swift\icu-[VERSION]`.
=> WiX: move install location of runtime

platforms/Windows/CustomActions/SwiftInstaller/Headers/scoped_raii.hh, platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc, platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj
The `std::filesystem::copy_file` implementation uses `CopyFileW` which
will copy the source to the destination.  If the destination is a
symbolic link, the link will be followed even if we are trying to
overwrite the destination.
Copy the source file renamed to the destination directory and then move
it into place.  The temporary file is named using a UUID as
`GetTempFileW` cannot be used properly here - the parent path is limited
to MAX_PATH - 14 characters, and using `GetTempPath` may provide a path
on a different volume which introduces a new race condition.  This
temporary file is then renamed into the destination by using the
`SetFileInformationByHandle` using the under-documented
`FileRenameInfoEx` to use the POSIX semantics for the rename ensuring
that the file replacement is …
=> SwiftInstaller: be more aggressive about file replacement

platforms/Windows/devtools.wxs, platforms/Windows/icu-amd64.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk.wixproj, platforms/Windows/toolchain.wixproj, platforms/Windows/toolchain.wxs
The previous names created an unnecessary number of variables.  This
cleans up the variables in the hopes that we can star exposing features
into the installer.  Take the opportunity to homogenise the manifests,
using similar names for cabinets, naming patterns, and make install
roots configurable even though that is not exposed via a UI.
Additionally add missing files for Swift Package Manager while
restructuring the MSI packages.  Furthermore, mark Debug Information
features as sub-features as they do not make sense as standalone
features.
=> WiX: correct naming for WiX rules

platforms/Windows/installer.wixproj, platforms/Windows/installer.wxs
This adds the ability to include "optional" MSIs to the chain.  Optional
MSIs are currently always installed as we do not have the UI for feature
selection in the boot-strapper, but can be subsequently removed from the
"Add Remove Programs" control panel.  This will enable the distribution
of the x86 SDK and runtime.
=> WiX: add some more control over the MSI chain

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs
This change was introduced in apple/swift#42081.
=> Rename _MatchingEngine to _RegexParser.

platforms/Windows/runtime.wxs, platforms/Windows/sdk.wxs
These files are not part of the 5.6 release.
=> WiX: remove _Distributed references

platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc
This corrects the file handle to the temporary file to be opened with a
shared disposition, drop write privileges as we will not modify the
file, and correct the destination path.  We were previously overwriting
the temporary file with itself, which made the operation meaningless.
=> CustomActions: correct destination path and permissions

platforms/Windows/devtools.wxs, platforms/Windows/icu-amd64.wxs, platforms/Windows/icu-x86.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/toolchain.wxs
Adjust the packaging to use component groups and components per file.
This should enable repair to behave properly as each component can only
have a single key file which is repaired.
=> WiX: create component groups and components

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs
Correct the case on the swiftmodule directory name which would prevent
Swift from finding the correct swiftmodule.  We would fail to realize
this installation issue on Windows without a clean installation as the
filesystem is case insensitive.
The x86 manifest missed the directory path for the swiftmodule for
Dispatch.  Correct that while fixing the dispatch swiftmodule.
=> WiX: correct Dispatch.swiftmodule spelling, x86 builds

platforms/Windows/toolchain.wxs
We should package up swift-api-digester and swift-symbolgraph-extract.
The former is needed to ensure that we can pass the swift-driver test
suite on a distributed toolchain.
=> WiX: package up additional tools on Windows

platforms/Windows/toolchain.wxs
Package up the features.json into the toolchain distribution.  This is
consulted by the swift-driver during execution.  The test suite
execution identified the missing file.
=> WiX: add missing features.json to the toolchain

platforms/Windows/CustomActions/SwiftInstaller/Sources/swift_installer.cc, platforms/Windows/devtools.wxs, platforms/Windows/icu-amd64.wxs, platforms/Windows/icu-x86.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/toolchain.wxs
Update the 5.7 installer manifest to match the current main version.  This is primarily cleaning up the structural issues in the MSI which helps with MSI/bootstrapper sizing as well as packages up missing items.  The custom action is made more aggressive for updates as well.
=> 5.7 updates

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs
Adjust the location of the swift modules to overlap across SDKs.  The
directory form of the swift module can easily overlap and co-exist.  Now
that the driver has learnt to scan the non-architecture dependent location
in addition to the architecture location dependent path, we can unify
the swiftmodule content in the SDK to a simpler layout.  The layout now
is:
~~~
SDKROOT
`- usr
`- lib
`- swift
`- [platform]
+- [module].swiftmodule
|   `- [triple].{swiftdoc,swiftmodule,swiftinterface}
`- [arch]
`- [import library]
~~~
On Windows, it would be preferable to further remove the intermediate
platform as we have that information earlier in the path.
Subsequent work remains to now ensure that the package manager will
similarly allow the XCTest swift modules to collapse.
While in theory it is …
=> WiX: remove extraneous architecture in search path

platforms/Windows/sdk-x86.wxs
Correct the manifest quoting of a string.
=> WiX: add a missing `"`

platforms/Windows/runtime-arm64.wxs, platforms/Windows/sdk-arm64.wxs
Add a variant of the manifest for the ARM64 SDK.  Now that the ARm64 SDK
can be built in its entirety, this is needed for the CI side of the work.
=> WiX: add Windows SDK packaging manifest for ARM64

platforms/Windows/sdk-x86.wxs
The symbol for the location was mismatched in case which broke the
build.  Correct the spelling.
=> WiX: correct typo in the install location

platforms/Windows/devtools.wixproj, platforms/Windows/icu.wixproj, platforms/Windows/installer.wixproj, platforms/Windows/runtime.wixproj, platforms/Windows/sdk.wixproj, platforms/Windows/toolchain.wixproj
We would previously depend on votive to provide the versioned
non-isolated installation of the `Wix.targets` project for the wix
targets definitions.  Instead update the wixproj files to scan both the
non-isolated and the isolated installations to enable us to build
without the votive dependency.  This allows us to reduce another
dependency on Visual Studio towards just the build tools.
=> WiX: drop dependency on votive

platforms/Windows/icu-arm64.wxs
The ICU packaging manifest was missed in the initial set of packaging
manifests for ARM64.  Add the missing file.
=> WiX: add missing runtime arm64 component manifest

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs
There were references to components which have been converted to
`ComponentGroup`s to enable repairs to reinstall files when necessary.
This requires that the references be updated as well.  Due to the
inability to include debug info, we did not catch the issues in the
ARM64 and AMD64 cases, and the X86 builds are not enabled on swift.org
yet.
=> WiX: correct component references

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
Add the missing `module.modulemap` for the `SwiftRemoteMirror` library
which is required to make use of the module.  This restores the ability
to build `swift-inspect` with a release toolchain.
=> WiX: add missing `module.modulemap` for SwiftRemoteMirror

platforms/Windows/CustomActions/SwiftInstaller/SwiftInstaller.vcxproj
With this we now get a default value for the `PlatformToolset` property
which will be configured based on the toolset that is installed.
Subsequently, the developer no longer needs to specify the value when
building the installer.
=> WiX: setup the `PlatformToolset` value to the default

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-x86.wxs
Cherry-pick some changes from main for component group references and the installation of the SwiftRemoteMirror modulemap which is required for building additional tooling.
=> ComponentGroup references and modulemap fixes

shared/ICU/CMakeLists.txt, shared/ICU/icupkg.inc.cmake
This adds a CMake based build for ICU.  This is motivated by Windows
where we can avoid having to install a large number of tools in order to
build ICU by rewriting the build system in CMake.
This is a stopgap solution to the fact that ICU does not a CMake based
build.  The project has been trying to switch to a CMake based for
nearly 4 years now [1].
This allows building ICU on Windows without having to setup and
configure cygwin to get access to autotools and without having to do
stage and coordinate the data build and the MSVC build.  This also
allows the use of ninja to build which speeds up the build of ICU, as
well as enables easy cross-compilation.  Additionally, this allows for a
more homogeneous build of Swift as nearly every other project builds
with CMake.  There are a number …
=> shared: add CMake based build rules for ICU

platforms/Windows/devtools.wxs, platforms/Windows/runtime.wxs, platforms/Windows/sdk.wxs
WiX project for Swift 5.5 for Windows refers to some components which are not present in a 5.5 snapshot. This patch removes nonexistent components and allows us to build the complete installer.
=> WiX: _Distributed and swift-collections are not part of 5.5

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
We were not packaging clangd.exe into the toolchain distribution which
is required for SourceKit-LSP.  Add the binary into the ARM64 and AMD64
packages.
=> WiX: package up clangd on Windows

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs
Reverts apple/swift-installer-scripts#145
This is currently forcefully being built as static, revert the packaging change.
=> Revert "Update Installer Scripts for sourcekit-lsp to Include SwiftSyntax"

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
This library has been removed from the Swift tree as of apple/swift@2d07f382c5a51834b63273539a2dd9e6a7ae6ea2.  Update the manifest to remove the references to permit building the packaging once again.
=> Windows: remove `_InternalSwiftSyntaxParser` from packaging

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs
SPM introduced new libraries in
apple/swift-package-manager@e26417cfa1ee117cf789b195c82459189e62ca70 and apple/swift-package-manager@b30ba0bc97eae2a0bb75cf491272c99926f1bc51 but failed to update the packaging rules resulting in an unusable distribution of SPM.  Update the manifest to include the libraries.
=> WiX: repair the Windows packaging for SPM

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs
Add the swiftCxx module into the runtime.  This is required by any code which imports `Cxx`.
=> WiX: package Cxx into the runtime

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
Package up the SDK contents for the C++ support module. This is required to enable use of the C++ interop functionality.
=> WiX: package Cxx and CxxShims in the SDK

platforms/Windows/sdk-x86.wxs
The changes in 4b08ef66638e0af99137c0b287a1d509e1a7fc6d failed to adjust the i686 paths due to copy-paste replication from the x86_64 target. Additionally, a typo would further fail to resolve locations.  This allows packaging the x86 SDK once again.
=> WiX: repair the x86 SDK packaging

platforms/Windows/sdk-arm64.wxs
Correct copy-paste errors that prevented the ARM64 SDK from being packaged.
=> WiX: repair ARM64 SDK packaging

platforms/Windows/devtools.wixproj
Ensure that we encode the correct value for the product for the devtools MSI.
=> WiX: correct substitution for product version

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
The toolchain can statically link Yams as there is a single user of the library.  This internalisation of the library allows us to save ~256KB of space.
=> WiX: remove Yams from the toolchain distribution

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
Move the import libraries for other components into the appropriate component groups.  This cleans up the llbuild component.
=> WiX: shuffle around non-llbuild components

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
Enable statically linking the swift-argument-parser library
SwiftArgumentParserToolInfo into SwiftAgumentParser as there is only a
single user of the library.
=> windows: update toolchain manifest for swift-argument-parser

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs
These files are no longer part of the manifest as we can use static linking for this module reducing the disk size by ~50KB.
=> WiX: remove IndexStoreDB from manifest

platforms/Windows/WiXCodeSigning.targets
While looking through this file I noticed that only the "SignBundle" target was missing a DependsOnTarget clause. All the others had it so seems reasonable for "SignBundle" to also.
=> Add DependsOnTargets to SignBundle insignia target

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
Since apple/swift-tools-support-core#377 converts TSCLibc into a static library, remove the entry from the packaging manifest to match.  We can now statically link this library and since there will be no dynamic lib we cannot package that.
=> WiX: remove `TSCLibc` from the packaging manifest

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs
Remove the swift-crypto contents from the installer manifest as this library can be built statically and linked accordingly into SPM as there is a single consumer of it.  This will help reduce the binary size.
=> WiX: remove SwiftCrypto from the installer manifest

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
This has been made static with apple/swift-llbuild#852.  Adjust the packaging rules accordingly.
=> WiX: remove `llbuild.dll` from toolchain distribution

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
The layout of the XCTest directories on Windows is currently inconsistent between local builds and installed builds. This change resolves the inconsistency by updating swiftmodule directory location for XCTest from:
`XCTest\usr\lib\swift\windows\%ARCH%\XCTest.swiftmodule`
To
`XCTest\usr\lib\swift\windows\XCTest.swiftmodule`
This allows us to use the same include path on all architectures and matches other standard modules. SPM was previously updated accordingly here: https://github.com/apple/swift-package-manager/pull/4300 but the related #119 did not update the paths for `XCTest`.
=> Move installed XCTest.swiftmodule up one directory on Windows

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/sdk.wixproj
With the install rules for Swift now packaging up the auxiliary SDK files as they are used by the compiler directly, simplify the packaging rules and remove the dependency on the checked out copy of the Swift repository.
=> WiX: adjust the packaging rules for the Windows SDK

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
This was removed on main, remove this here as well.
=> WiX: remove _Runtime and Reflection packaging

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-x86.wxs
These dlls and their pdbs do not exist anymore but were still inconsistently getting packaged for some architectures on Windows. Sometimes only the pdb, sometimes only the dll. Presumably this didn't fail in the CI because old files were still present on the machine.
Also fixes a typo: `wwiftRemoteMirror` > `swiftRemoteMirror`
=> Stop packaging swiftReflection and swift_Runtime in the Windows installer.

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs, platforms/Windows/devtools.wixproj, platforms/Windows/installer.wixproj, platforms/Windows/installer.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/runtime.wixproj, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/sdk.wixproj, platforms/Windows/swift-format-amd64.wxs, platforms/Windows/swift-format-arm64.wxs, platforms/Windows/swift-format.wixproj, platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs, platforms/Windows/toolchain.wixproj
Migrates the Windows installer to WiX v4, SDK-style project and consuming WiX from Nuget, meaning that it doesn't need to be installed on the machine anymore. This also unblocks the arm64 installer.
I ran the WiX v4 converter extension in VS, then tweaked the output to minimize the diff. Many elements are slightly different in v4:
- wixprojs are sdk-style, with `<Project>`. They require `msbuild -restore`.
- wix extensions are served through nuget via `<PackageReference>`
- `Compressed="yes"` is now default.
- `TARGETDIR` should not be defined anymore
- Condition syntax is slightly different
- `Absent="disallow"` became `allowAbsent="no"`
How tested:
- Built locally
Pending related changes to consuming repos. (adding `-restore` to the msbuild invocation)
=> Migrate the Windows installer to WiX v4

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/swift-format-amd64.wxs, platforms/Windows/swift-format-arm64.wxs, platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
The rules around `<SetDirectory>` changed between WiX v3 and v4, so our port resulted in the INSTALLDIR defaulting to `C:\` instead of either `C:\Program Files\swift` or `C:\Library`.
Changes:
- For the runtime, use `<StandardDirectory>` to root in `ProgramFiles`, and capitalize `Swift` for consistency with all other programs
- For stuff installed under `C:\Library`, use `<SetDirectory>` + `<Directory>` as a means of rooting at `WindowsVolume`, also change the customizable installation path to the `C:\` underneath `Library` (so the installer will write the `Library` directory under the users' path rather than start at the `Developer` directory)
How tested:
- Rebuilt and installed runtime + sdk msi's to their default locations and to overriden locations, then installed the full installer. …
=> Fix default Windows install directory regression from WiX v4 port

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs, platforms/Windows/devtools.wixproj, platforms/Windows/installer.wixproj, platforms/Windows/installer.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/runtime.wixproj, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/sdk.wixproj, platforms/Windows/swift-format-amd64.wxs, platforms/Windows/swift-format-arm64.wxs, platforms/Windows/swift-format.wixproj, platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs, platforms/Windows/toolchain.wixproj
In order to be able to stamp the version information into the installer properly, we need to migrate to WiX 4.0.  Cherry-pick the migration changes to the 5.9 release branch.
=> WiX: backport the WiX 4.0 migration for 5.9

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/runtime.wixproj, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/swift-format-amd64.wxs, platforms/Windows/swift-format-arm64.wxs, platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs, platforms/Windows/toolchain.wixproj
The preference for distribution of the debug information should be a symbol server which would permit the matching of the binary to the proper symbols for the particular build.  This is important as the total debug information is ~10x larger than the distribution itself and would add a very large overhead to the download sizes.
=> WiX: remove the support for packaging for Debug Info

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
Include the `swiftToCxx` content as compiler resources for the Swift compiler for the distribution.  This is part oft the C++ interop work.
Fixes: apple/swift#63446
=> WiX: add swiftToCxx content to the toolchain distribution

platforms/Windows/devtools.wixproj, platforms/Windows/installer.wixproj, platforms/Windows/runtime.wixproj, platforms/Windows/sdk.wixproj, platforms/Windows/swift-format.wixproj, platforms/Windows/toolchain.wixproj
Wix v4.0.0 has now been published on [nuget](https://www.nuget.org/packages/WixToolset.Sdk). Time to migrate from the release candidate.
=> Migrate Windows installer to Wix v4.0.0 release

platforms/Windows/installer-amd64.wxs, platforms/Windows/installer-arm64.wxs
The ability to distribute the debug information with the installer has been removed as the total size of the debug information vastly outsizes the packaging of the toolchain (~7x).  The traditional way to distribute debug information on Windows is via a symbol server with indexing via SaaS such as Azure Packages.  Remove the now defunct property setting.
=> WiX: remove unnecessary MSI Property

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs
This is part of the Manifest API in SPM and expected to be present. Package this into the distribution as well.
=> WiX: package up CompilerPluginSupport module

platforms/Windows/devtools-amd64.wxs, platforms/Windows/devtools-arm64.wxs, platforms/Windows/installer-amd64.wxs, platforms/Windows/installer-arm64.wxs, platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs, platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
Restructure the packaging to be more homogeneous and concise.
- Swift Software Development Kit
* Swift Compiler Tools
* Swift Developer Tools
* Swift Windows Runtime (AMD64|ARM|ARM64|x86)
* Swift Windows SDK (AMD64|ARM|ARM64|x86)
This gives a more concise description that is also easier to understand
and map.  This sets up the path for further refinement of the installer
to provide more control over the installed components.
We do not suffix the Software Development Kit nor Compiler and Developer
Tools as there will be a singular version that matches the host that is
installed.  Therefore, there is no value in differentiating that.
However, multiple SDKs and Runtimes may be present, so identify the
architecture for them.
=> WiX: rewrite the package identities

platforms/Windows/sdk.wxs
This adjusts the Windows installation logic after the changes in https://github.com/apple/swift/pull/66765
rdar://110788977
=> [cxx-interop] CxxShim files became arch-independent

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
This adjusts the Windows installation logic after the changes in https://github.com/apple/swift/pull/66765
rdar://110788977
=> WiX: CxxShim files became arch-independent (#213)

platforms/Windows/sdk/sdk.wxs
This file was not being packaged into the installer, which gives us an incomplete module.
Partially fixes: apple/swift#67462
=> WiX: package `libcxxstdlibshim.h` on Windows

platforms/Windows/sdk/sdk.wxs
This is the first standard library component which is static only.  Add this new module to the distribution.
=> WiX: package CxxStdlib on Windows

platforms/Windows/shared/swift.en-us.wxl
The x86 runtime was missing the product identifier.  This should repair the x86 build.
=> WiX: add missing product name

platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
This adds the final missing component of the C++ interop to the 5.9 release now that it is enabled in the build.
=> WiX: add CxxStdlib to the Windows packaging

platforms/Windows/rtl/lib/rtllib.wxs, platforms/Windows/sdk/sdk.wxs
Adjust for Cxx being built statically now (which removes the runtime distribution content and puts the library into the SDK).  The C++ interop support now matches the Darwin and Linux platforms and distributes it as static libraries as the interface is fragile still.
=> WiX: adjust Cxx module packaging

platforms/Windows/bundle/installer.wxs, platforms/Windows/bundle/theme.xml, platforms/Windows/sdk/sdk.wxs, platforms/Windows/shared/swift.en-us.wxl
Also disable modify button in ARP.
=> Add checkboxes per SDK for redist MSMs.

platforms/Windows/sdk/sdk.wxs
We should use the version emitted into the `swift` rather than `swift_static` since we are linking against the dynamically linked variant
=> WiX: adjust the packaging for CxxStdlib

platforms/Windows/bundle/theme.xml, platforms/Windows/shared/swift.en-us.wxl
Adjust the L&F to maintain the aspect ratio that we previously had (4:3).  This also adjusts some of the spacing to make it more uniform and adjusts the location of the side banner.  The banner is currently shorter than the desired height, but is expected to be replaced with an appropriately sized image soon.  It also enables the feature selection items for the ARM64 and X86 SDKs.
=> WiX: adjust the installer UI

platforms/Windows/runtime-amd64.wxs, platforms/Windows/runtime-arm64.wxs, platforms/Windows/runtime-x86.wxs, platforms/Windows/sdk-amd64.wxs, platforms/Windows/sdk-arm64.wxs, platforms/Windows/sdk-x86.wxs
These are now built statically for the dynamic standard library and should be packaged as such.
=> WiX: adjust the packaging for Cxx, CxxStdlib

platforms/Windows/sdk/sdk.wxs
The Cxx and CxxStdlib modules are fragile and should not distribute the interfaces.  This currently actually causes a packaging failure.  Update the manifest to remove the entries.
=> WiX: remove swiftinterfaces for fragile components

platforms/Windows/toolchain-amd64.wxs, platforms/Windows/toolchain-arm64.wxs
With FetchContent changes in swift repo, SwiftIDEUtils.dll is no longer installed in the toolchain.
=> Remove SwiftIDEUtils from Windows toolchain

platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs
Packages the VC++ redistributable and installs it as part of the toolchain install on Windows, since this is a dependency. Note that this will pop a UAC prompt because that installer is per-machine.
This is the [Microsoft-recommended approach](https://learn.microsoft.com/en-us/cpp/windows/deployment-in-visual-cpp?view=msvc-170): run the vcredist installer to install it globally (which makes it serviceable by microsoft), and don't uninstall it when uninstalling the toolchain since other apps may depend on it.
This requires [build script changes](https://github.com/compnerd/swift-build/pull/664) to take effect, but is backwards compatible with build scripts that don't specify the new properties.
I consciously departed from `ALL_CAPS` naming of properties because the MSBuild standard is …
=> Install the VC++ redistributable as part of the Swift toolchain installer

platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs
The compilers and runtime depend on the runtime. Introduce a dependency on the runtime for the VC runtime, which is a dependency for the build tools.  This should allow us to be more self-contained (there is a dependency on WinSDK and VS if not cross-compiling to another platform).
=> WiX: package the VC redist as part of the installation

platforms/Windows/bundle/installer.wxs
The runtime library must be installed as the Swift compiler depends on this for the macros support as well as the driver being written in Swift. This is a hard dependency for the build tools.
=> WiX: no longer honour `OptionsInstallRtl`

platforms/Windows/bld/bld.wxs
Add the swift syntax runtime libraries and swiftmodules to enable macros on Windows.
=> WiX: package up macro support libraries

platforms/Windows/bld/bld.wxs
This adds an additional DLL to the image.  The compiler is now able to vend enough of the swift-syntax library to enable building the LSP without adding a second copy of the parser.  This shaves ~6MiB off of the LSP binary.
=> WiX: add `SwiftIDEUtils.dll` to the image

platforms/Windows/rtl/lib/rtllib.wxs, platforms/Windows/sdk/sdk.wxs
We were previously missing the RegexBuilder module in the SDK distribution.  Package this up as it should be available on Windows.
=> WiX: package RegexBuilder into the SDK on Windows

platforms/Windows/bld/bld.wxs, platforms/Windows/rtl/lib/rtllib.wxs, platforms/Windows/sdk/sdk.wxs
Include the Observable module in the SDK and runtime.  Additionally,
include the observable macros for the toolchain into the build tools.
=> WiX: package Observable into the distribution

platforms/Windows/Directory.Build.props, platforms/Windows/bld/bld.wxs, platforms/Windows/cli/cli.wxs, platforms/Windows/dbg/dbg.wxs, platforms/Windows/ide/ide.wxs, platforms/Windows/rtl/msi/rtlmsi.wxs, platforms/Windows/rtl/msm/rtlmsm.wxs, platforms/Windows/sdk/sdk.wxs, platforms/Windows/shared/shared.wxs
`<Package>` versions must be merely uint16's with no trailing `-`. We used to handle this in `build.ps1` on a per-wixproj basis before the refactoring that made `installer.wixproj` drive the whole build. The `<Bundle>` version still keeps using the semantic version suffix because that is supported.
=> WiX: avoid using extended versioning on the MSIs

platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs, platforms/Windows/rtl/msi/rtlmsi.wixproj, platforms/Windows/rtl/msi/rtlmsi.wxs, platforms/Windows/shared/swift.en-us.wxl
The Swift runtime depends on the Visual C++ runtime. We currently call the `vcredist.exe` installer, as recommended by Microsoft, but this is a per-machine installer so it makes our per-user installer require elevation. I tried switching to using the vcredist merge modules, but they seem to reference machine-global paths like System64 and it causes build errors. We're left with the option to package the vcruntime dlls directly in the msi. We're not including them in the Swift runtime msm's since application developers may choose to distribute their vcruntime differently.
The new `VCRedistDir` property is optional so that this remains backwards compatible with build scripts that don't specify it.
Result:
=> Package the VC runtime dlls directly

platforms/Windows/bld/bld.wxs
Add the missing header and modulemap definition for the SwiftBridging module in Swift.  This improves the C++ interop coverage on Windows.
=> WiX: package up `SwiftBridging` C++ module

platforms/Windows/bld/bld.wxs, platforms/Windows/cli/cli.wixproj, platforms/Windows/cli/cli.wxs, platforms/Windows/shared/shared.wxs
Add support to package up DocC in the windows distribution.  This is the last large component that was missing.  At this point, the toolchain distribution is generally speaking complete with:
- Preprocessor (clang)
- Assembler (IAS)
- C/C++/Swift Compiler (clang/clang++/swiftc)
- Linker (lld)
- Binary Utilities (LLVM)
- Debugger (LLDB)
- REPL
- Package Manager (SwiftPM)
- Runtime Inspection Tools (swift-inspect)
- LSP (sourcekit-lsp)
- Code Formatter (swift-format)
- Documentation Tools (DocC)
- Additional IDE integration Tools (lldb-vscode)
- Redistributables (MSMs)
- Runtime (host-only)
- SDKs (AMD64, ARM64, X86)
=> WiX: package up DocC conditionally

platforms/Windows/dbg/dbg.wxs
Include the static mirror library as part of the debugging tools. This library is useful for building diagnostics tooling and is not currently used in the core toolchain for building code or performing CI tasks.
=> WiX: package `_InternalSwiftStaticMirror` on Windows

platforms/Windows/bld/bld.wxs
This is scanned for and used by newer CMake releases. Include it in the toolchain distribution packaging.
=> WiX: package and distribute `clang-scan-deps`

platforms/Windows/sdk/sdk.wxs
The module is becoming non-resilient in https://github.com/apple/swift/pull/70953.
=> WiX: Remove _RegexParser's .swiftinterface from the SDK.

platforms/Windows/bld/bld.wxs
Add the missing dependency for sourcekit-lsp as per apple/swift-installer-scripts#280.
=> WiX: package SwiftRefactor for sourcekit-lsp

platforms/Windows/cli/cli.wxs
This reflects https://github.com/apple/swift-package-manager/pull/7467, adapting to https://github.com/apple/swift-package-manager/pull/7494
=> [6.0] Add PackageModelSyntax.dll

platforms/Windows/SideBySideUpgradeStrategy.props
Introduce a new bundle upgrade code to get 6.0 installers built.
=> WiX: define new upgrade code for 6.0

shared/ICU/CMakeLists.txt
- Emit the stub data library into a subdirectory to prevent collisions
- Remove the generated output from byproducts, it is the output
=> ICU: tweak build rules slightly

shared/ICU/CMakeLists.txt
This is needed to build Android ICU on Windows, using https://github.com/apple/swift/pull/72014
=> [icu] add a BUILD_DATA flag to let android build skip building data

shared/ICU/CMakeLists.txt
When cross-compiling to a different platform from Windows, we should explicitly suffix the executable binary for invocation.
=> ICU: explicitly suffix tools for cross-compiling support

shared/ICU/CMakeLists.txt
This lets us build an android data library using windows ICU tools.
The original pkgdata invocation invoked LIB.exe on windows and was building for the windows target. Let's make an assembly file using genccode instead.
=> ICU: build data library using genccode

platforms/Windows/bld/bld.wxs
This adds an additional DLL to the image. 'SwiftMacros.dll' includes macro implementations for stdlib. e.g. 'TaskLocal'
Resolves rdar://128092675.
=> WiX: add `SwiftMacros.dll` to the image

platforms/Windows/bld/bld.wxs
Cherry-pick https://github.com/apple/swift-installer-scripts/pull/295 into `release/6.0`
* **Explanantion**: This adds an additional DLL to the Windows toolchains. 'SwiftMacros.dll' includes macro implementations for stdlib. e.g. 'TaskLocal'
* **Scope**: Standard library macros in Windows toolchains
* **Risk**: Low. Just adding a DLL where it was supposed to be.
* **Testing**: Locally confirmed that stdlib macros `TaskLocal` work
* **Issue**:  rdar://128092675
* **Reviewer**: @compnerd
=> [6.0] WiX: add `SwiftMacros.dll` to the image

platforms/Windows/SideBySideUpgradeStrategy.props, platforms/Windows/android_sdk/android_sdk.wixproj, platforms/Windows/android_sdk/android_sdk.wxs, platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs, platforms/Windows/bundle/theme.xml, platforms/Windows/readme.md, platforms/Windows/sdk/sdk.wxs, platforms/Windows/shared/swift.en-us.wxl
This change packages the Android SDKs that can be built using build.ps1 on windows into MSIs, which are then added to the toolchain's installer.
At the moment it covers aarch64 only, I'm adding and testing other arches and will update the PR with them as well.
For future follow-up:
- Fix the 'CxxStdlib' build issue for Android and add it to the installer. (https://github.com/apple/swift/issues/73855)
=> Package and bundle Android SDKs into the windows toolchain installer

platforms/Windows/bld/bld.wxs
Include `features.json` from clang to allow tooling to detect features supported by the C/C++ compiler.
Fixes: swiftlang/swift#74634
=> WiX: package `features.json` for clang

platforms/Windows/android_sdk/android_sdk.wxs
swiftlang/swift#74186 has been marked resolved. Address the FIXME to enable packaging the module again.
=> WiX: package up Synchronisation on Android ARMv7

platforms/Windows/android_sdk/android_sdk.wxs
With the introduction of APINotes to workaround issues in the Bionic headers, we need to package up the additional content. Add the APINotes so that we can build swift-foundation.
=> WiX: package up Android auxiliary files

platforms/Windows/android_sdk/android_sdk.wxs, platforms/Windows/rtl/lib/rtllib.wxs, platforms/Windows/sdk/sdk.wxs
This updates the Windows/Android scripts to account for the Foundation re-core which involves:
- New C modules `_foundation_unicode` and `_FoundationCShims` added to the SDK (with `.lib` files on Windows)
- New Swift modules `_FoundationCollections.swiftmodule`, `FoundationEssentials.swiftmodule`, and `FoundationInternationalization.swiftmodule` added to the SDK (with `.lib` files on Windows)
- New binaries for `_FoundationICU`, `FoundationEssentials`, and `FoundationInternationalization`
Additionally, this updates the paths for `Foundation`/`FoundationXML`/`FoundationNetworking` to account for the new structure of the swift module (a directory with per-arch files rather than files put into per-arch directories)
=> Update Windows/Android installer scripts for swift-foundation re-core

platforms/Windows/cli/cli.wxs
This is required with recent changes to SPM. Add the missing library to the toolchain distribution.
Fixes: #318
=> WiX: add `InternalCollectionsUtilities` to the distribution

platforms/Windows/sdk/sdk.wxs
This is needed after https://github.com/apple/swift-foundation-icu/pull/39
Explanation: After https://github.com/apple/swift-foundation-icu/pull/39 landed in foundation-icu, foundation-icu's modulemap started to depend on new headers from that PR. They need to be installed by the windows SDK installer in order for the modulemap to be valid in the windows toolchain distribution for Swift.
Scope: windows SDK installer
Risk: Low
Testing: toolchain build, and build of windows toolchain in a github workflow
Reviewer: @compnerd
Main branch PR: https://github.com/swiftlang/swift-installer-scripts/pull/321
=> [swift 6][windows] installer script: add new foundation ICU headers to SDKs

platforms/Windows/bld/bld.wxs
Include a prebuilt copy of the Foundation macros in the toolchain distribution on Windows to match the desired behaviour.
=> WiX: add Foundation macros to the build tools

platforms/Windows/bundle/installer.wxs, platforms/Windows/readme.md
This is a surprising interaction between variable types. Variables set at the command line are set as string types. The variables in the bundle are numeric (either `1` or `0` to match the semantics of check boxes). The original install condition
(`InstallCondition="OptionsInstall.*"` would evaluate the condition as a string, where _any_ value would evaluate as `true`. To force a comparison, where Burn will coerce values more like expectations, perform an explicit equality check.
=> WiX: correct the install conditions

platforms/Windows/bld/bld.wxs
The Windows build tools should include `llvm-ml`, a replacement for `ml` which is the assembler.
=> WiX: include `llvm-ml` in the build tools

platforms/Windows/android_sdk/android_sdk.wixproj, platforms/Windows/android_sdk/android_sdk.wxs
Conditionally include DS2 in the Android SDK when building the MSI with `-p:ANDROID_INCLUDE_DS2=true` passed to `msbuild`. Has no impact on the generated installer if this property is not set.
Related to the `build.ps1` changes in https://github.com/swiftlang/swift/pull/76113
Verified by manually invoking `msbuild` against locally built swift toolchain (with local changes to build DS2) with and without `-p:ANDROID_INCLUDE_DS2=true` and manually inspected the output MSI file with MSI Viewer. Done for aarch64, x86_64, i686, and armv7.
```
MSBuild.exe -nologo -restore -maxCpuCount -p:BaseOutputPath=S:\b\installer\ -p:Configuration=Release -p:SignOutput=false -p:PLATFORM_ROOT="S:\b\arm64\Android.platform" -p:SDK_ROOT="S:\b\arm64\Android.platform\Developer\SDKs\Android.sdk" …
```
=> [android] optionally include DS2 in Android SDK

platforms/Windows/bld/bld.wixproj, platforms/Windows/bld/bld.wxs, platforms/Windows/shared/shared.wxs
this directory contains clang's resource headers that are needed by the clang embedded inside of the swift compiler, as it assumes its clang resources are in usr/lib/swift/clang, as opposed to standalone clang looking in usr/lib/clang/<clang_version>
=> [windows] add usr/lib/swift/clang to the toolchain installer

platforms/Windows/bundle/installer.wxs, platforms/Windows/bundle/theme.xml, platforms/Windows/rtl/lib/rtllib.wxs, platforms/Windows/rtl/msi/rtlmsi.wxs, platforms/Windows/rtl/msm/rtlmsm.wxs, platforms/Windows/shared/swift.en-us.wxl
Add an option to elide `plutil` from installation. This is a tiny binary that is useful, but distributions may wish to remove it. Adjust the installer labels and also force install the runtime now that the compiler depends on it.
Fixes: #340
=> WiX: optionalise `plutil` through a hidden option

platforms/Windows/sdk/sdk.wxs
These two libraries are now built with library evolution enabled.
See https://github.com/swiftlang/swift/pull/77559
=> [cxx-interop] Include swiftinterface files for Cxx and CxxStdlib

platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs
Treat all architectures equally and provide an option for all of them. This allows us to programmatically invoke the build target with the correct set of flags.
=> WiX: handle all installed architectures similarly

platforms/Windows/SideBySideUpgradeStrategy.props, platforms/Windows/android_sdk/android_sdk.wixproj, platforms/Windows/android_sdk/android_sdk.wxs, platforms/Windows/bld/bld.wixproj, platforms/Windows/bld/bld.wxs, platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs, platforms/Windows/bundle/theme.xml, platforms/Windows/readme.md, platforms/Windows/sdk/sdk.wxs, platforms/Windows/shared/shared.wxs, platforms/Windows/shared/swift.en-us.wxl
This PR cherry-picks the installer changes that are needed to build the installer that contains the android SDKs in the swift 6 branch.
=> [release/6] cherry-pick Android installer changes needed to build swift 6 installer

platforms/Windows/bld/bld.wixproj, platforms/Windows/bld/bld.wxs, platforms/Windows/cli/cli.wixproj, platforms/Windows/cli/cli.wxs, platforms/Windows/dbg/dbg.wixproj, platforms/Windows/ide/ide.wixproj, platforms/Windows/ide/ide.wxs, platforms/Windows/readme.md
As the Windows build has evolved, we have built up a complete toolchain image and removed the need for the separate `DEVTOOLS_ROOT`. This simplifies the packaging manifest and associated MSBuild files.
=> WiX: remove references to `DEVTOOLS_ROOT`

platforms/Windows/readme.md
We cannot build DocC everywhere yet (primarily Windows ARM64 cannot be built due to the use of SPM). Document the properties that we use to control the packaging with regards to DocC.
=> WiX: update documentation to include DocC properties

platforms/Windows/dbg/dbg.wixproj, platforms/Windows/dbg/dbg.wxs, platforms/Windows/readme.md, platforms/Windows/shared/shared.wxs
We now can always build swift-inspect, remove the option to exclude swift-inspect. Shuffle the tool into the main toolchain installation and remove the additional support that the fragmented swift-inspect handling required.
=> WiX: make swift-inspect required for Windows

platforms/Windows/android_sdk/android_sdk.wixproj, platforms/Windows/android_sdk/android_sdk.wxs, platforms/Windows/bundle/installer.wixproj, platforms/Windows/bundle/installer.wxs, platforms/Windows/readme.md, platforms/Windows/sdk/sdk.wixproj, platforms/Windows/sdk/sdk.wxs
Uniformly use `sdk.[os].[arch].{msi,cab}` for the name of the files and `INCLUDE_[os]_[arch]_SDK` to indicate that the SDK should be included. This makes both Windows and Android similar in their handling and naming.
=> WiX: adjust SDK handling for homogeneity

platforms/Windows/SideBySideUpgradeStrategy.props
Add a new upgrade identifier for the 6.1 release.
=> WiX: add an identifier for the 6.1 branch

platforms/Windows/cli/cli.wxs
`SourceControl` has been made a shared library in
swiftlang/swift-package-manager#8124.
=> WiX: Update the manifest to include SourceControl.dll

platforms/Windows/bundle/theme.xml
Case-sensitively match the checkbox and the variable names so that the command line option like "OptionsInstallIDE=0" works.
=> Fix the Windows installer command line options

platforms/Windows/sdk/drd/sdk.wixproj
Properties defined in `shared.wixproj` are used in the Android SDK packaging project.
=> [Android] Reference `shared.wixproj`

platforms/Windows/cli/cli.wxs
`SourceControl` has been made a shared library in
swiftlang/swift-package-manager#8124.
(cherry picked from commit 345b660f1f017ac541cfe292b51739cf0288fb58)
=> [6.1][package_manager] Add SourceControl dll

platforms/Windows/bld/bld.wxs
Incorporate the `ToolchainInfo.plist` into the toolchain distribution to associate an identifier with the toolchain for ease of working with parallel installations.
=> WiX: add `ToolchainInfo.plist` to the build tools

platforms/Windows/cli/cli.wxs
This library is able to be internalised into the SPM libraries that are using it. As this is a single use library, this overall helps reduce the size of the distribution and requires fewer libraries to be distributed.
=> WiX: remove SystemPackage from toolchain distribution

platforms/Windows/cli/cli.wxs
This helper script enables the use of `git clang-format` for changes which is helpful for re-formatting commits, including those for the Swift toolchain.
=> WiX: package up `git-clang-format`

platforms/Windows/ide/ide.wxs
Install the SourceKit plugin, added by https://github.com/swiftlang/sourcekit-lsp/pull/1906 into the Windows toolchains.
rdar://142909870
=> Install the SourceKit plugin into Windows toolchains

platforms/Windows/sdk/drd/sdk.wxs, platforms/Windows/sdk/win/sdk.wxs
This adds a new configuration file for the SDKs to avoid a spurious warning from swift-driver.
=> WiX: package up SDKSettings.json in the SDKs

platforms/Windows/sdk/win/sdk.wxs
This just adds some comments to categorise what is being distributed by the SDK package manifest.
=> WiX: categorise segments of the SDK packaging

platforms/Windows/bld/bld.wxs
This packages up the educational notes for distribution with the toolchain. It is yet unclear if this should be broken out into an optioanl MSI to allow installation of the documentation on demand rather than as an always available option. This should at least ensure that we distribute the user facing documentation that can be accessed from the compiler.
=> WiX: add educational notes to the windows packaging

platforms/Windows/sdk/win/sdk.wxs
Rather than dealing with the path adjustments due to the SDK install and stage differences, simply re-package from the staged location. This allows us to have a working toolchain earlier and simplifies for the installer rules.
=> WiX: begin packaging the SDK from the staged directory

platforms/Windows/sdk/CDispatch.wxi, platforms/Windows/sdk/drd/sdk.wxs, platforms/Windows/sdk/win/sdk.wxs
The core dispatch headers are uniform across the SDKs. Ideally we would also be able to share the "os" headers, but they are installed into a separate directory and we cannot simply include them for the restructuring.
=> WiX: extract CDispatch module definition

platforms/Windows/sdk/drd/sdk.wxs
Adjust the install location for ds2 and pick it up from the new location.
=> WiX: update naming and location for DS2

platforms/Windows/bld/bld.wxs
I'm removing this note in https://github.com/swiftlang/swift/pull/79509/commits/f1492fe55372712bf90c4b822b2705fddcaec5d2; the restriction was lifted in SE-0362.
Starting in Swift 6.2, educational note identifiers should be stable and should not be removed in later toolchains. However, Swift 6.2 will be the first toolchain version to make that promise, so it's okay to clean up this educational note now.
=> [WiX] Remove an outdated educational note from Windows packaging.

platforms/Windows/sdk/drd/sdk.wxs, platforms/Windows/sdk/win/sdk.wxs
Switch from `.swiftmodule` to `.swiftinterface` files for Swift Testing (`Testing.swiftmodule`). Related to and motivated by https://github.com/swiftlang/swift-testing/pull/982.
=> Switch to .swiftinterface files for Testing module

platforms/Windows/dbg/dbg.wxs
This adds a new utility to the toolchain - `swift-synthesize-interface`.
For now, consider it a debugging utility as it is not used during the
normal compilation pipeline and thus is not a build tool. This is not
something that is normally used during CI pipelines and does not fit
into the CLI tools. As this is not currently integrated into the IDE, we
don't consider it an IDE tool either.
=> WiX: package and distribute `swift-synthesize-interface`

platforms/Windows/sdk/CDispatch.wxi, platforms/Windows/sdk/_FoundationCShims.wxi, platforms/Windows/sdk/_FoundationUnicode.wxi, platforms/Windows/sdk/drd/sdk.wxs, platforms/Windows/sdk/win/sdk.wxs
Adjust the source path for the C headers to reflect a fully staged toolchain installation to keep up with the build.ps1 changes.
=> WiX: adjust paths for C headers

platforms/Windows/sdk/drd/sdk.wxs, platforms/Windows/sdk/win/sdk.wxs
Properly version the Testing frameworks. This finally moves the last of the legacy versioning (`development`) to numeric form. The `0.0.0` version is used as a placeholder equivalent for development releases.
=> WiX: adjust for versioning

platforms/Windows/sdk/drd/sdk.wxs
The product version variable was typoed. Due to the lack of packaging in swift.org CI on PRs, this was not caught. Repair this for the nightly builds.
=> WiX: correct typo in Android SDK packaging

platforms/Windows/sdk/drd/sdk.wxs
The Android ARMv7 build will properly install the modules at this point without a separate triple for the modules. Update the rules accordingly bringing the ARMv7 inline with the other Android SDKs. The only outlier remaining would be `ds2` which should adopt the same triple.
=> WiX: simplify the Android ARMv7 rules

platforms/Windows/sdk/win/sdk.wxs
The import libraries are architecture specific. As we do not currently merge the import libraries, we embed them into an architecture specific directory. This adjusts the lookup path as we have started moving the files rather than copying them. This makes the installer packaging more strict about expecting the path to the final destination.
=> WiX: adjust the scanned paths for the import libraries

platforms/Windows/SideBySideUpgradeStrategy.props
This is required to properly package the 6.2 build.
=> WiX: Add an identifier for the 6.2 branch

platforms/Windows/platforms/android/android.wxs
- Correct the case for the XCTest inclusion check.
- Correct indentation for DS2 inclusion.
- Correct feature names for architecture support.
=> WiX: adjust the android platform packaging

platforms/Windows/bld/bld.wixproj, platforms/Windows/bld/bld.wxs
Remove the extra library packaging which was a workaround for mimalloc adding a reference to foreign architecture modules.
=> WiX: remove workaround for mimalloc

platforms/Windows/cli/cli.wxs
Builds on https://github.com/swiftlang/swift-installer-scripts/pull/417 - only the second commit is new
Ensure the Windows installer includes the resources bundled in https://github.com/swiftlang/swift-build/pull/488
=> Install the SwiftPM/Swift Build resources in /usr/share/pm

platforms/Windows/cli/cli.wxs
This is my first time touching the windows installer, so there may be some silly mistakes here. Opening the PR now so I can run some tests
=> Add SwiftBuild dlls to cli installer component alongside SwiftPM

platforms/Windows/cli/cli.wxs
Cherry-pick of https://github.com/swiftlang/swift-installer-scripts/pull/418
Explanation:
Cherrypick changes to install Swift Build libraries/resources which are used by SwiftPM
Risk: Low - SwiftPM on release/6.2 is not (yet) using this content when built with CMake, so for now this is purely adding new files to the installer.
Reviewed By: @compnerd
Testing: Cross-repo testing w/ Windows toolchain job
=> [6.2] Install Swift Build content for use by SwiftPM

platforms/Windows/platforms/windows/windows.wxs
Ensure that these files are packaged into the appropriate cabs. When supporting the online installer, selecting (or de-selecting) an architecture should allow us to shave off the download for the components that are architecture specific. Make the default disk id (1) explicit as we prepare to add an experimental SDK.
=> WiX: adjust the disk ids for the windows sdk

platforms/Windows/cli/cli.wxs
`SwiftSDKCommand.dll` is now required by some binaries to run.
=> WiX: adjust SPM build dependencies

platforms/FreeBSD/Readme.md, platforms/FreeBSD/makePackage
Swift should be distributed to FreeBSD users as a .pkg file which can be installed using pkg, the system package manager. This allows for a better user experience because it handles installing all of the required dependencies as well as placing the compiler in the user's PATH.
To create a FreeBSD package, we should have a script that automates the process of creating one. This commit adds such a script. It is designed to be invoked by the CI system, but can also be invoked by an end user.
=> Add installation packaging script for FreeBSD

platforms/Windows/bld/asserts/bld.asserts.wixproj, platforms/Windows/bld/bld.wxi, platforms/Windows/cli/asserts/cli.asserts.wixproj, platforms/Windows/cli/cli.wxi
This is a follow up change to #428. In this PR we are making component group IDs reflect the variant in the name they are carrying. 
There is no functional change in this change, changes are only to component ids.
=> Reflect variant name in component group ids

platforms/Windows/bld/asserts/bld.asserts.wixproj, platforms/Windows/bld/bld.wxi, platforms/Windows/platforms/CDispatch.wxi, platforms/Windows/platforms/_FoundationCShims.wxi, platforms/Windows/platforms/_FoundationUnicode.wxi, platforms/Windows/platforms/android/android.wxs, platforms/Windows/platforms/windows/windows.wixproj, platforms/Windows/platforms/windows/windows.wxs, platforms/Windows/shared/shared.wxs, platforms/Windows/shared/swift.en-us.wxl
This packages the experimental runtime builds to allow us to statically link against the standard library. This will be used to allow us to bootstrap the early swift-driver on Windows.
=> WiX: package the experimental runtime builds

platforms/Windows/platforms/windows/windows.wxs
Swift-Collections [switched](https://github.com/apple/swift-collections/pull/470) to using the full module triple. We're updating Swift to use a newer Swift-Collections, so updating the filenames here.
Fixes: swiftlang/swift-foundation#1230
=> WiX: Update FoundationCollections module names

platforms/Windows/platforms/android/android.wxs
We need to now specify the disk ID for dispatch components. We were missing one for the shared headers.
=> WiX: correct packaging for Android SDK on Windows

platforms/Windows/platforms/android/android.wxs
We now properly generate the swiftmodules for FoundationCollections. Update the packaging manifest to account for that. This was fixed on Windows but not Android.
=> WiX: update android packaging for changes to the SDK build

platforms/Windows/bld/asserts/bld.asserts.wixproj, platforms/Windows/bld/bld.wxi, platforms/Windows/cli/asserts/cli.asserts.wixproj, platforms/Windows/cli/cli.wxi, platforms/Windows/dbg/dbg.wxi, platforms/Windows/ide/ide.wxi, platforms/Windows/shared/shared.wxs
This is a follow up change to #428. In this PR we are making directory IDs reflect the variant in the name of the install directory (e.g. `Swift\Toolchains\6.2.0+Asserts\usr`). 
There is no functional change in this change, it is just directory ids. Directory names and which components are installed to which directories should not be changed. 
This should make it easier to add new variants by following the same pattern, and will allow us to parametrize authoring that is shared between variants.
Naming convention:
- `ToolchainsVersioned` became `ToolchainsVersionedAsserts` -- this is our top-level toolchain install directory like `Swift\Toolchains\0.0.0+Asserts`
- Subdirectories like `_usr_share` became `toolchains_asserts_usr_share` to reflect the full path at install time …
=> Reflect variant name in directory ids

platforms/Windows/platforms/windows/windows.wxs
Include the new build of Distributed into the static experimental SDK.
=> WiX: package up Distributed in the experimental SDK

platforms/Windows/bld/bld.wxi
A change i missed in https://github.com/swiftlang/swift-installer-scripts/pull/432 causing us not to add the toolchain in the env path.
=> Fix broken env path setting in installer

platforms/Windows/platforms/windows/windows.wxs
This renames the current default Windows SDK content to the `Legacy` prefixed name. This is in preparation to package up the new experimental SDK content. The experimental SDK is meant to become the default and this will simplify the transition.
=> WiX: rename `SwiftRemoteMirror` to `LegacySwiftRemoteMirror`

platforms/FreeBSD/makePackage
We need to make two changes:
- First, the package `e2fsprogs-libuuid` is no longer shipped and the standard `libuuid` is used instead. We should therefore update the package manifest to reflect this change in the dependencies.
- Second, hard-coding package versions into the script is not very scaleable and will be a maintainence burden. Instead, we should ensure that the minimum package version required is whatever the build machine running this script has.
=> Update FreeBSD packaging script

platforms/Windows/platforms/windows/windows.wxs
This adds the SwiftRemoteMirror to the packaging on Windows to round out the new SDK. With this piece, it might be possible to host the entire Swift toolchain with a SxS enabled runtime.
=> WiX: package up the new SwiftRemoteMirror builds

platforms/Windows/platforms/windows/windows.wxs
Re-sort (lexicographically) the components, remove unnecessary disk attributes, and some minor component renaming to match the general naming. This should ease the migration between the legacy and experimental SDKs.
=> WiX: a collection of small clean up to the packaging rules

platforms/Windows/Directory.Build.props, platforms/Windows/Directory.Build.targets, platforms/Windows/SideBySideUpgradeStrategy.props, platforms/Windows/bundle/installer.wixproj, platforms/Windows/platforms/windows/windows.wixproj, platforms/Windows/platforms/windows/windows.wxs, platforms/Windows/rtl/shared/lib/rtl.shared.lib.wixproj, platforms/Windows/rtl/shared/lib/rtl.shared.lib.wxs, platforms/Windows/rtl/shared/msi/rtl.shared.msi.wixproj, platforms/Windows/rtl/shared/msi/rtl.shared.msi.wxs, platforms/Windows/rtl/shared/msm/rtl.shared.msm.wixproj, platforms/Windows/rtl/shared/msm/rtl.shared.msm.wxs, platforms/Windows/rtl/static/msm/rtl.static.msm.wixproj, platforms/Windows/rtl/static/msm/rtl.static.msm.wxs
This pull request introduces experimental shared and static runtime installer modules for Windows, with supporting build logic and packaging for multiple architectures. The changes add new WiX project files, update build properties, and integrate these new runtimes into the Windows installer and merge module pipelines.
**Experimental Runtime Packaging and Build Integration**
* Added new WiX project and source files for experimental shared runtime (`rtl.shared.lib.wixproj`, `rtl.shared.lib.wxs`), merge module (`rtl.shared.msm.wixproj`, `rtl.shared.msm.wxs`), and MSI installer (`rtl.shared.msi.wixproj`, `rtl.shared.msi.wxs`), as well as for the static runtime merge module (`rtl.static.msm.wixproj`, `rtl.static.msm.wxs`). These include component definitions for distributing Swift runtime …
=> WiX: package up the experimental dynamic SDK and the runtime redistributables

platforms/Windows/platforms/windows/windows.wxs
Changed in https://github.com/swiftlang/swift-installer-scripts/pull/461, we are using an undefined properties `Install...Platform` reverting to the correct property name `Install...SDK`
=> WiX: use the right variable name in feature install condition

platforms/Windows/rtl/static/msm/rtl.static.msm.wxs
This fixes the packaging step for builds like `-WindowsSDKArchitectures "Arm64"`
- When choosing runtime roots, use `ProductArchitecture`, not `sys.BUILDARCH`. `sys.BUILDARCH` derives from `Platform`, which is always x86.
- Updates rotated conditions
=> WiX: Fix single-arch packaging for static experimental SDK

platforms/Windows/cli/cli.wxi
The package manager runtime installation adjusted for the split build installs the module with the target triple named thick module format. Adjust the packaging rules to integrate that into the image.
=> WiX: adjust the packaging rules for the SPM runtime
