platforms/Linux/Fedora/README.md

I changed the way to create the container image to be compatible with both Docker and Podman

Changed container image creation command

---

platforms/Linux/amazonlinux/2/swift-lang.spec
platforms/Linux/centos/7/build_rpm.sh
platforms/Linux/centos/7/swift-lang.spec
platforms/Linux/centos/8/swift-lang.spec
platforms/Linux/shared/RPM/metadata.inc

* Build CMake v3.19.6 
* Fix the CentOS 7 to source the .bashrc
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.0 or higher is required.  You are running version 2.8.12.2
```

Add support for CMake repo in the spec files

---

README.md

Updated the README to reflect new directory structure.

update README to reflect new directory structure

---

platforms/Windows/runtime.wxs
platforms/Windows/sdk.wxs

This has now been enabled and is being built.  Add this to the manifest for
installation packaging.

Windows: package _StringProcessing on main

---

platforms/Linux/RPM/Fedora/35/swiftlang.spec
platforms/Linux/RPM/Fedora/rawhide/swiftlang.spec

Had wrong character ($) instead of (%)

Fixed typo in spec file

---

platforms/Linux/RPM/Amazonlinux/2/docker-compose.yaml
platforms/Linux/RPM/Amazonlinux/2/swiftlang.spec
platforms/Linux/RPM/Centos/7/docker-compose.yaml
platforms/Linux/RPM/Centos/7/swiftlang.spec
platforms/Linux/RPM/Centos/8/docker-compose.yaml
platforms/Linux/RPM/Centos/8/swiftlang.spec

motivation: cleanup
changes:
* better name for docker container
* group source moving together

small cleanup for centos and amazon linux

---

platforms/Windows/runtime.wxs
platforms/Windows/sdk.wxs

Update the installer manifest for the distributed module renaming.

Update SDK/Runtime packaging

---

.gitignore

Ignore vim swap files by default.

gitignore: ignore editor temporary files

---

platforms/Windows/devtools-amd64.wxs
platforms/Windows/devtools-arm64.wxs

Add swift-package-registry and swift-package-collections to the Windows distributions.

WiX: package additional SPM tools

---

platforms/Windows/devtools.wixproj
platforms/Windows/installer.wixproj
platforms/Windows/runtime.wixproj
platforms/Windows/sdk.wixproj
platforms/Windows/swift-format.wixproj
platforms/Windows/toolchain.wixproj

Migrate Windows installer to Wix v4.0.0 release

---

platforms/Windows/sdk/sdk.wxs

See https://github.com/apple/swift/pull/68118.
rdar://107572302

WiX: Package `std.apinotes` into the Windows installer

---

platforms/Windows/toolchain-amd64.wxs
platforms/Windows/toolchain-arm64.wxs

This adds the necessary modules to support macros on Windows.

WiX: package up swift syntax for macro support

---

platforms/Windows/toolchain-amd64.wxs
platforms/Windows/toolchain-arm64.wxs

Squashed cherry-pick of #246.
-----
Adds the necessary modules to support macros on Windows.

[5.9.1] Enable macros for Windows in 5.9.1

---

platforms/Windows/bld/bld.wxs
platforms/Windows/rtl/lib/rtllib.wxs
platforms/Windows/sdk/sdk.wxs

Include the Observable module in the SDK and runtime.

WiX: package Observable into the distribution

---

platforms/Windows/SideBySideUpgradeStrategy.props

(cherry picked from commit 38c61d579565f783e784f621f33b9499346f79df)

WiX: add a new bundle upgrade code for 5.10 release

---

platforms/Windows/bld/bld.wxs

See https://github.com/apple/swift/pull/72186

[cxx-interop] Add `usr/include/module.modulemap` file

---

platforms/Windows/cli/cli.wxs

This reflects https://github.com/apple/swift-package-manager/pull/7467

Add PackageModelSyntax.dll

---

platforms/Windows/bld/bld.wxs

Update for https://github.com/apple/swift/pull/73725

[Windows] Add _CompilerSwiftSyntax libs and plugin servers

---

platforms/Windows/rtl/lib/rtllib.wxs
platforms/Windows/sdk/sdk.wxs

Cherry pick of #312 for release/6.0 branch.

[6.0] Update Windows/Android installer scripts for swift-foundation re-core

---

platforms/Windows/Directory.Build.targets
platforms/Windows/bld/bld.wixproj
platforms/Windows/bundle/installer.wixproj
platforms/Windows/cli/cli.wixproj
platforms/Windows/dbg/dbg.wixproj
platforms/Windows/ide/ide.wixproj
platforms/Windows/rtl/lib/rtllib.wixproj
platforms/Windows/rtl/msi/rtlmsi.wixproj
platforms/Windows/rtl/msm/rtlmsm.wixproj
platforms/Windows/samples/HelloMergeModule/hellomm.wixproj
platforms/Windows/sdk/sdk.wixproj
platforms/Windows/shared/shared.wixproj

Addresses security vulnerabilities: https://www.firegiant.com/blog/2024/3/22/wix-security-releases-available-redux/
Not tested locally, leaving it to CI.

Update to WiX 4.0.5

---

platforms/Windows/android_sdk/android_sdk.wixproj

Update the WiX image to resolve a security vulnerability.

WiX: update android SDK to WiX 4.0.5

---

platforms/Windows/android_sdk/android_sdk.wxs
platforms/Windows/sdk/sdk.wxs

This is needed after https://github.com/apple/swift-foundation-icu/pull/39

[windows] installer script: add new foundation ICU headers to SDKs

---

platforms/Windows/bld/bld.wxs
platforms/Windows/sdk/sdk.wxs

Cherry-pick #317 into release/6.0

[6.0][Windows/Android] Add swift-testing

---

platforms/Windows/bld/bld.wxs
platforms/Windows/sdk/sdk.wxs

Cherry-pick #327 into `release/6.0.0`

[6.0.0][Windows/Android] Add swift-testing

---

platforms/Windows/platforms/windows/windows.wxs

Include the new build of Observation into the static experimental SDK.

WiX: package up Observation in the experimental SDK

---

platforms/Windows/platforms/windows/windows.wxs

Include the new build of _Differentiation into the static experimental SDK.

WiX: package up _Differentiation in the experimental SDK

---

platforms/Windows/platforms/windows/windows.wxs

Remove unnecessary disk id specification and add the condition for the ARM64 slice of the experimental SDK.

Simple correction
